name: Telegram Bot

on:
  push:
    branches:
      - main  # o il branch che usi

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "python-telegram-bot[webhooks]"

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Inserisci il token come Secret su GitHub
          PROJECT_DOMAIN: ${{ secrets.PROJECT_DOMAIN }}  # Inserisci il dominio pubblico come Secret
          PORT: 8443
        run: python bot.py
